GET http://localhost:8080/api/v1/sakupay/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWt1cGF5IiwiZXhwIjoxNjk3NTgyMTY2LCJpYXQiOjE2OTc1Nzg1NjYsIlVzZXJuYW1lIjoiYXBpIn0.4kLqF2tqpzJzOhOVU0z9vbBJhTvm7bnBxt82YCwb7DQ
###
GET http://localhost:8080/api/v1/sakupay/users/ebe5df1e-c886-4849-8741-0fc2a1e511e/bills HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWt1cGF5IiwiZXhwIjoxNjk3NTczMDg3LCJpYXQiOjE2OTc1Njk0ODcsIlVzZXJuYW1lIjoicmFsc3MifQ.IXYrljsVzHcvMtSCgyCYeBMYUT_lmYKVTv7Weve7TjM
###
POST  http://localhost:8080/api/v1/sakupay/users/7499a3aa-24ad-4299-b683-8c266dcbb1c7/bills HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWt1cGF5IiwiZXhwIjoxNjk3NTc0MjY3LCJpYXQiOjE2OTc1NzA2NjcsIlVzZXJuYW1lIjoiYWRtaW4ifQ.GVqOlQqnwoBAzDg0T2F7IPxO_jmNeCuS1eKKILQLZDM
Content-Type: application/json

{
    "billDetails" : {
        "name"      : "riska",
        "category"  : "data",
        "description" : "top up",
        "merchant" : "shopee"
    },
    "total" : 600000,
    "dueDate" : "2023-10-18T02:10:47.623588Z",
    "status" : "true"
}
###
GET http://localhost:8080/api/v1/sakupay/users/7499a3aa-24ad-4299-b683-8c266dcbb1c7/cards HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWt1cGF5IiwiZXhwIjoxNjk3NTgyMTY2LCJpYXQiOjE2OTc1Nzg1NjYsIlVzZXJuYW1lIjoiYXBpIn0.4kLqF2tqpzJzOhOVU0z9vbBJhTvm7bnBxt82YCwb7DQ
Content-Type: application/json

{
   "cardNumber":"3213212235222523",
   "cardHolderName": "mandiri",
   "expirationDate":"2023-10-18T02:10:47.623588Z",
   "balance":50000,
   "cvv":"213"
}

###
POST http://localhost:8080/api/v1/sakupay/auth/register HTTP/1.1
Content-Type: application/json

{
	"username":"api",
	"email":"littleey27@gmail.com",
	"password":"api",
	"firstName":"Rafly",
	"lastName":"Mahendra",
	"PhoneNumber":"08727729712"
}
###
POST http://localhost:8080/api/v1/sakupay/auth/login HTTP/1.1
Content-Type: application/json

{
	"username":"api",
	"password":"api"
}
###
GET http://localhost:8080/api/v1/sakupay/users/c371312f-c21c-4fa8-af47-1c83f91583cb HTTP/1.1
###
PUT http://localhost:8080/api/v1/sakupay/users/2cbb92da-1022-4136-b753-e94e1aa75883 HTTP/1.1
Content-Type: application/json

{
	"username":"admin",
	"email":"admin@gmail.com",
	"password":"admin",
	"firstName":"Rafly",
	"lastName":"Mahendra",
	"PhoneNumber":"0761245"
}
###
POST http://localhost:8080/api/v1/sakupay/auth/register HTTP/1.1
Content-Type: application/json

{
	"username":"admin",
	"email":"admin@gmail.com",
	"password":"admin",
	"firstName":"Rafly",
	"lastName":"Mahendra",
	"PhoneNumber":"0761245"
}
###
DELETE http://localhost:8080/api/v1/sakupay/users/31ec27fe-c5e0-4b41-bfb6-31b4b5ab8eef HTTP/1.1

GET http://localhost:8080/api/v1/sakupay/transaction HTTP/1.1

###
POST http://localhost:8080/api/v1/sakupay/users/7499a3aa-24ad-4299-b683-8c266dcbb1c7/transactions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWt1cGF5IiwiZXhwIjoxNjk3NTc0MjY3LCJpYXQiOjE2OTc1NzA2NjcsIlVzZXJuYW1lIjoiYWRtaW4ifQ.GVqOlQqnwoBAzDg0T2F7IPxO_jmNeCuS1eKKILQLZDM
Content-Type: application/json

{
	"TransactionType":"deposit",
	"Amount":20000,
	"Description":"untuk tabungan"
}
###
GET http://localhost:8080/api/v1/sakupay/users/b45b1210-9cb7-437d-bd01-7833e270e672/transactions/53e3070d-3d34-4d07-851a-67dff6cfc6ce HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWt1cGF5IiwiZXhwIjoxNjk3NDYzODI4LCJpYXQiOjE2OTc0NjAyMjgsIlVzZXJuYW1lIjoicmFsc3MifQ.reLJwdK-qSbs7NKnhltDDtq05F240R4xQjH5_4ZMzu4
